services:
  - type: web
    name: snacktrack-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: snacktrack-db

databases:
  - name: snacktrack-db
    databaseName: snacktrack_db
    user: snacktrack_user
    plan: free # upgrade to paid in production
