services:
  - type: web
    name: snack-track-backend
    env: docker
    plan: free
    branch: deploy
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: API_URL
        value: https://snack-track-backend.onrender.com
